
name: Release

on:
  push:
    branches: [ master ]
jobs:
  release:
    runs-on: ubuntu-latest
    name: Generate release
    steps:
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Generate release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
