
name: Release

on:
  push:
    branches: [ master ]
jobs:
  release:
    name: Generate release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18']
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install, build
      run: |
        npm install
        npm run build
        npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

